# Generated by Django 5.1.5 on 2025-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
