# Generated by Django 5.1.5 on 2025-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dollo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="file",
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.CharField(default="Unknown Address", max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
