# Generated by Django 5.1.5 on 2025-02-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dollo", "0002_remove_student_file_student_address_student_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
