# Generated by Django 5.1.5 on 2025-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dollo", "0004_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="speed",
            field=models.IntegerField(),
        ),
    ]
